### ISSUE TITLE
Mantophasma, etc gender neuter

### ISSUE THREAD

**Issue by sjl197** [sfg-taxonpages/mantophasmatodea#1]
Flag from iNaturalist indicates all genera ending ~phasma are neuter
https://www.inaturalist.org/flags/586525

e.g. under Mantophasma, you have
Mantophasma omatakoense Zompro & Adis, 2006
Mantophasma paresisensis (Klass, Picker, Damgaard, van Noort & Tojo, 2003)

reflecting the neuter for the first, then the masculine/feminine for the latter

**Comment by hhopkins77** [comment]
Stuart--we have to enter the original as printed in the literature, and then later cite a reviser who corrects the problem--and a later paper did catch and correct this which we missed. Thank you!

**Comment by sjl197** [comment]
First, many thanks for looking into this and making some updates. I understand the need to reflect the originals even if include aspects later deemed misspellings, malformation etc. I also understand what can be practical challenges of implementing such complexities via the Taxonworks interface! Some other thoughts below on what you've now kindly implemented.

For the "Sclerophasma paresisensis" with originally malformed suffix - perhaps further to your new edits, please see that the revised neuter suffix was elsewhere published in combination with the original genus (i.e. as Sclerophasma paresisense) in a phylogeny paper by Damgaard, Klass, Picker,Buder 2008 Mol. Phyl. Evol. 47(2). Can you please reflect both spellings as synonyms (where the change to Sclerophasma paresisense is a justified emendment), as otherwise without mention it then helps cause clashes on other downsteam databases, ie. GBIF has that then misduplicated as both Sclerophasma paresisense and Sclerophasma paresisensis (see https://www.gbif.org/fr/species/1421152)

As for the generic placement, thankfully both genera can be treated as feminine as you surely noticed. Technically, yes - Zompro & Adis, 2006 had already previously recombined as Mantophasma paresisense, but even if Damgaard et al. 2008 was deemed the most recent publication - what i mean by this that isn't it that your catalog can simply favour whichever generic combination, provided that is nomenclaturally available. In either genus, the modification of the suffix to neuter would be mandatory per ICZN (if following the regulations on gender agreement which you obviously are), so wouldn't technically need to be 'published' nor need a citation for the suffix emendation be practically implemented (i.e. listed and favored) on Taxonworks [but i don't think the backend has anything to help specify such cases when suffix emendations are not published]. Point is, i think will be helpful to also list Sclerophasma paresisense as a synonym, and for that you can for example Damgaard et al. 2008, but in my understanding of ICZN for modifiable suffixes, then you don't need to cite anything in cases like that.

Then further, if agree to that principal, there's multiple other "-phasma" genera, such as  Austrophasma, Hemilobophasma, etc where the suffixes don't yet reflect neuter. For these, the only exception that comes to mind is if the gender of any of these genera are explicitly stated as something besides neuter in their original descriptions. Again, i don't think there's need to have the neuter suffix as published for any of these to be cataloged in neuter format, but please notice that again, at least some how the neuter combination published in Damgaard et al. 2008, i.e. Austrophasma caledonense, Hemilobophasma montaguense, etc,

**Comment by hhopkins77** [comment]
The complete taxonomic history of every species has not been entered, though that is the goal. We need the scientific community, and especially users of this data, to provide any information they can about missing/incorrect data as you have done. We'll do our best to get it in, and get mistakes corrected.

Now that I think about what you have written here I think I remember that a reviser is not required for an incorrect Latin ending--I get in the habit of looking for citations for every change! I will bring your synonymy request to the next meeting and see if it is possible before I work through the other "phasma" issues. Thanks again for your input.
